ariane/ariane/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

ariane/web/urls.py
from django.urls import path, include
from web import views

app_name='web'

urlpatterns=[
    path('',views.HomePage.as_view(), name='home'),
    path('about/',views.AboutPage.as_view(), name='about'),
    path('project/', views.ProjectPage.as_view(),name='project'),
    path('products/', views.ProductPage.as_view(),name='product'),
    path('products/solar-series/', views.SwhPage.as_view(), name="swh"),
    path('products/heatpump-series/', views.HeatpumpPage.as_view(), name="heatpump"),
    path('products/pump-filter/', views.PumpPage.as_view(), name="pump"),
    path('our-partners/', views.PartnerPage.as_view(), name="partner"),
    path('artikel/', views.ArtikelPage.as_view(), name="artikel-swh"),
    path('artikel/swh-1/', views.ArtikelPageSwh1.as_view(), name="artikel-swh-1"),
]

ariane/web/models.py
from django.db import models

# Create your models here.

ariane/web/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomePage(TemplateView):
    template_name = 'web/index.html'

class AboutPage(TemplateView):
    template_name = 'web/about.html'

class ProjectPage(TemplateView):
    template_name = "web/project.html"

class ProductPage(TemplateView):
    template_name = 'web/product.html'

class SwhPage(TemplateView):
    template_name = "web/swh.html"

class HeatpumpPage(TemplateView):
    template_name = "web/heatpump.html"

class PumpPage(TemplateView):
    template_name = 'web/pump.html'

class PartnerPage(TemplateView):
    template_name = 'web/partner.html'

class ArtikelPage(TemplateView):
    template_name = 'web/artikel-swh.html'

class ArtikelPageSwh1(TemplateView):
    template_name = 'web/artikel-swh-1.html'

    

ariane/templates/web/artikel-swh-1.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
    <section class="artikel-content">
        <div class="container">
            <h3><u>Prinsip kerja Solar Water heater</u></h3>
            <img class="rounded mx-auto d-block pt-5 pb-1" src="{% static 'web/img/Thermosiphon.jpg' %}" alt="">
            <p class="pt-3">Solar water heater bekerja dengan sistem thermosiphon. Prinsip dari thermosiphon adalah proses perpindahan panas yang bersifat pasif atau tanpa bantuan perana luar seperti contoh pompa. Perpindahan panas ini terjadi
                dengan proses konveksi natural. Proses ini menggunakan air sebagai medium perpindahan panas. Air di kollektor dipanaskan oleh sinar matahari.
                Air panas memiliki massa yang lebih ringan daripada air dingin. Sehingga air panas akan naik dari kollektor atau kaca ke tangki bagian atas. Sebaliknya air dingin
                akan turun ke kollektor dan dipanaskan kembali oleh sinar matahari. Penting untuk diperhatikan, bahwa tangki air harus minimal terletak di atas kollektor untuk memungkinkan proses sirkulasi air.
            </p>
            <h3><u>Keuntungan Ekonomi</u></h3>
            <p class="pt-3">Dengan menggunakan Solar water heater, memanaskan air dapat menggunakan energi matahari yang gratis.
                Menurut study dari MIT International Journal of mechanical engineering, sebuah solar water heater dengan kapasitas 100 liter dapat
                mencegah emisi gas CO2 sebesar 1.5 ton per tahun.
            </p>
        </div>
    </section>
{% endblock %}

ariane/templates/web/artikel-swh.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
    <section class="artikel">
        <div class="container">
            <div class="row">
                <div class="col-3">
                    <img class="img-left" src="{% static 'web/img/swh-vacuum.jpg' %}" alt="swh-vacuum">
                </div>
                <div class="col-9">
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident illo quidem doloremque soluta enim veniam impedit consequatur modi, laboriosam quas.</p>
                    <a href="{% url 'web:artikel-swh-1' %}">selanjutnya</a>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-9">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non ipsum dolore optio error illo? Atque nesciunt vitae error fugiat, blanditiis quia unde voluptate soluta doloribus earum ipsam quidem distinctio consequuntur.</p>
                    <a href="#">Selanjutnya</a>
                </div>
                <div class="col-3">
                    <img class="img-right" src="{% static 'web/img/swh-vacuum.jpg' %}" alt="swh-vacuum">
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-3">
                    <img class="img-left" src="{% static 'web/img/swh-vacuum.jpg' %}" alt="swh-vacuum">
                </div>
                <div class="col-9">
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident illo quidem doloremque soluta enim veniam impedit consequatur modi, laboriosam quas.</p>
                    <a href="#">selanjutnya</a>
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

ariane/templates/web/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ariane</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'web/css/master.css'%}">
    <script src="https://kit.fontawesome.com/b588932b0e.js" crossorigin="anonymous"></script>

  </head>
  <body>
      <!-- Navbar starts  -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color: crimson;">
        <div class="container">
          <a class="navbar-brand fs-5 fw-bold text-white" href="{% url 'web:home' %}"><img src="{% static 'web/img/logo2.png' %}" alt="Ariane" width="40">Ariane</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link fs-5 text-white" href="{% url 'web:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-5 text-white" href="{% url 'web:about' %}">Company</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link fs-5 text-white" href="{% url 'web:artikel-swh' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Artikel
                </a>
                <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'web:artikel-swh' %}">Solar Water Heater</a>
                  <a class="dropdown-item" href="#">Heatpump </a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link fs-5 text-white" href="{% url 'web:product' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Products
                </a>
                <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'web:swh' %}">Solar series</a>
                  <a class="dropdown-item" href="{% url 'web:heatpump' %}">Heatpump series</a>
                  <a class="dropdown-item" href="{% url 'web:pump' %}">Booster Pump</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-5 text-white" href="{% url 'web:project' %}">Projects</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-5 text-white" href="{% url 'web:partner' %}">Our Partners</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-5 text-white" href="https://www.facebook.com/albert.koesnaidi"><i class="fab fa-facebook"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-5 text-white" href="https://www.instagram.com/albertkoesnaidi/?hl=en"><i class="fab fa-instagram"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- Navbar ends  -->
        {% block content %}

        {% endblock %}
    
      

      <!-- Footer starts  -->
      <footer class="footer text-center pt-5 pb-5">
        <div class="container">
          <div class="row text-white fw-bold">
            <div class="col text-start pb-2">
              
              <h3>Alamat</h3>
              <div class="footer-text">
                <p>Jl. Baliwerti no 46</p>
              <p>Surabaya</p> 
              <p>60175</p>
              </div>
            </div>
            <div class="col text-start pb-2">
              <h3>Kontak</h3>
              <div class="footer-text">
                <p>no telp: +62315343457</p>
                <p>no hp: +628140652050</p>
              </div>
            </div>
            <div class="col text-start pb-2">
              <h3>Social Media</h3>
              <div class="footer-text">
                <a href="https://www.facebook.com/albert.koesnaidi"><i class="fab fa-facebook"></i></a>
                <a href="https://www.instagram.com/albertkoesnaidi/?hl=en"><i class="fab fa-instagram"></i></a>
              </div-footer-text>
            </div>
          </div>
          <div class="row">
            <div class="col pt-1">
            </div>
          </div>
          <div class="row">
            <div class="col">
              <p>Copyrigth <i class="far fa-copyright"></i> Ariane Water Heater 2021</p>
            </div>
          </div>
        </div>
        
      </footer>
      <!-- Footer ends  -->
    


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

  </body>
</html>

ariane/templates/web/heatpump.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

    <section class="heatpump-text">
        <div class="container">
            <h3>Ariane Heatpump Water Heater</h3>
            <p>Heatpump water heater adalah alat yang digunakan untuk memindahkan panas dari suatu sumber energi panas ke tempat yang membutuhkan panas. Dalam hal ini Ariane heatpump water heater menggunakan sumber energi panas yang berupa udara di sekitar kita yang panas dan lembab. Prinsip kerja heatpump adalah seperti pendingin ruangan yang kita miliki sekarang ini. Panas dari udara sekitar dipindahkan ke air melalui kompressor dengan bantuan regrigerant. Oleh sebab itu heatpump memiliki effektivitas yang lebih tinggi daripada menggunakan seperti contoh boiler gas atau listrik. Sebagai dampak dari proses pemanasan air ini maka udara sejuk akan di produksi sebagai waste product dari heatpump dan dapat dipakai sebagai penyejuk ruangan</p>
        </div>
    </section>

    <section class="heatpump-swimming-pool">
        <div class="container">
            <h3 class="text-center">Swimming Pool</h3>
        </div>
    </section>

    <section class="heatpump-swimming-pool-product">
        <div class="container">
            <div class="row pt-4">
                <div class="col-sm-5">
                    <img id="swh-vacuum-img" src="{% static 'web/img/swh-vacuum.jpg' %}" alt="swh-vacuum">
                </div>
                <div class="col-7 fs-5">
                    <ul>
                        <li>Menggunakan R410a sebagai refrigerant yang ramah lingkungan</li>
                        <li>Menggunakan heat exchanger berbahan titanium untuk mengurangi korrosivitas</li>
                        <li>Dapat dipakai untuk mendinginkan dan memanaskan kolam rengana</li>
                        <li>dilengkapi dengan safety protection yang lengkap</li>
                    </ul>
                    <a href="{% static 'web/media/test.pdf' %}" download>broschure 100 ltr</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>broschure 200 ltr</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>broschure 300 ltr</a>
                </div>
            </div>
        </div>
    </section>

    <section class="heatpump-hotel">
        <div class="container">
            <h3 class="text-center">Commercial</h3>
        </div>
    </section>

    <section class="heatpump-hotel-product">
        <div class="container">
           
                <div class="row pt-4">
                    <div class="col-sm-7 fs-5">
                        <ul>
                            <li>Menggunakan refrigerant R410a yang ramah lingkungan</li>
                            <li>Mengadopsi sistem tube-in-tube heat exchanger sehingga memiliki COP yang tinggi</li>
                            <li>Dilengkapi dengan system safety protection yang lengkap</li>
                            <li>Dapat digunakan untuk sistem pemanasan dan pendinginan air</li>
                        </ul>
                        <a href="{% static 'web/media/test.pdf' %}" download>broschure 100 ltr</a>
                        <a href="{% static 'web/media/test.pdf' %}" download>broschure 200 ltr</a>
                        <a href="{% static 'web/media/test.pdf' %}" download>broschure 300 ltr</a>
                    </div>
                    <div class="col-sm-5">
                        <img id="swh-flat-img" src="{% static 'web/img/swh-flat.jpg' %}" alt="swh-vacuum">
                    </div>
                </div>
            
        </div>

    </section>

    <section class="heatpump-residential">
        <div class="container">
            <h3 class="text-center">Residential</h3>
        </div>
    </section>

    <section class="heatpump-residential-product">
        <div class="container">
            <div class="row pt-4">
                <div class="col-sm-5">
                    <img id="swh-vacuum-img" src="{% static 'web/img/swh-vacuum.jpg' %}" alt="swh-vacuum">
                </div>
                <div class="col-sm-7 fs-5">
                    <ul>
                        <li>Menggunakan refrigerant R410a yang ramah lingkungan</li>
                        <li>System Tube in shell heat exchanger sehingga tercapai COP yang maksimal</li>
                        <li>Dilengkapi dengan safety protection yang lengkap</li>
                        <li>Dapat digunakan untuk pemanasan dan pendinginan air</li>
                    </ul>
                    <a href="{% static 'web/media/test.pdf' %}" download>broschure 100 ltr</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>broschure 200 ltr</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>broschure 300 ltr</a>
                </div>
            </div>
        </div>
    </section>

    <section class="find-partner-banner">
        <div class="container">
            <a href="{% url 'web:partner' %}">Find Partners</a>
        </div>
    </section>

{% endblock %}

ariane/templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
<section class="header" id="header">
    <div class="home-content">
        <p class="text1" >Mari kita bersama-sama menjadikan bumi ini menjadi tempat yang lebih layak untuk dihuni</p>
       <!-- <a href="{% url 'web:product' %}">Artikel</a> -->
    </div>
</section>

<section class="ttg-kami">
  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Mengenal <span id="ttg-kami-span"> Ariane </span></h3>
        <p>Kami adalah penyedia jasa yang bergerak di bidang energi terbarukan. Kami spesialisasi untuk pemasangan pemanas air tenaga matahari dan heatpump. Dengan teknologi ini maka Anda tidak hanya bisa menyelamatkan bumi dari perubahan iklim yang berbahaya namum Anda dapat juga menghemat pengeluaran bulanan Anda</p>
        <a href="{% url 'web:about' %}">Tentang kami</a>
      </div>
      <div class="col">
        <img src="{% static 'web/img/logo-ariane.png'%}" alt="ariane logo">
      </div>
    </div>
    
  </div>

</section>

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#a9a9a9" fill-opacity="1" d="M0,224L1440,96L1440,320L0,320Z"></path></svg>
<section class="about" id="about">
    <h4 class="text-about">Mengapa kami</h4>
    <div class="container">
        <div class="row pb-2">
            <div class="col">
                <div class="box">
                    <h1 class="fw-bold text-center "><i class="fas fa-hourglass-half"></i></h1>
                <p class="text-center">Pengalaman selama 35 tahun di bidang pemanas air matahari</p>
                </div>
                 
            </div>
            <div class="col">
                <div class="box">
                    <h1 class="fw-bold text-center"><i class="far fa-smile"></i></h1>
                <p class="text-center">Kepuasan customer menjadi yang nomer satu bagi kami</p>
                </div>
            </div>
            <div class="col">
                <div class="box">
                    <h1 class="fw-bold text-center"><i class="fas fa-cogs"></i></h1>
                <p class="text-center">Pelayanan aftersales service yang sigap dan terpercaya</p>
                </div>
            </div>
        </div>
        <div class="row pt-5">
          <div class="col">
              <div class="box">
                  <h1 class="fw-bold text-center "><i class="fas fa-hand-holding-usd"></i></h1>
              <p class="text-center">Kami menawarkan product yang berkualitas dengan harga yang bersaing</p>
              </div>
               
          </div>
          <div class="col">
              <div class="box">
                  <h1 class="fw-bold text-center"><i class="fas fa-user-clock"></i></h1>
              <p class="text-center">Teknisi yang berkompetensi dengan jam terbang yang tinggi</p>
              </div>
          </div>
          <div class="col">
              <div class="box">
                  <h1 class="fw-bold text-center"><i class="fas fa-map-marked-alt"></i></i></h1>
              <p class="text-center">Kami menawarkan layanan ke seluruh nusantara</p>
              </div>
          </div>
      </div>
        
    </div>   
</section>

<section class="mission" id="mission">
 
    <div class="row">
      <div class="col">
        <h4 id="text-mission">Bisakah mengurangi biaya listrik rumah dan sekaligus mengurangi efek rumah kaca? temukan jawaban Anda pada artikel-artikel kami pada link di bawah ini</h4>
        <a href="{% url 'web:artikel-swh' %}">Artikel</a>
      </div>
      <div class="col">
        <img class="float-sm-end" id="green-energy-img" src="{% static 'web/img/green_energy.jpeg'%}" alt="green_energy">
      </div>
    </div>
  
</section>

<!-- Do not display this image at the moment
<section class="products" id="products">
    <h4 class="text-products text-center fw-bold pb-3">Products</h4>
    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem; color: black; border-radius: 10px;">
                <img src="{% static 'web/img/p1.jpg'%}" class="card-img-top" alt="p1">
                <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
              </div>
        </div>
        <div class="col">
            <div class="card" style="width: 18rem; color: black; border-radius: 10px;">
                <img src="{% static 'web/img/p2.jpg'%}" class="card-img-top" alt="p2">
                <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
              </div>
        </div>
        <div class="col">
            <div class="card" style="width: 18rem; color: black;border-radius: 10px;">
                <img src="{% static 'web/img/p3.jpg'%}" class="card-img-top" alt="p3">
                <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
              </div>
        </div>
    </div>
</section>
-->

<section class="projects" id="projects">
  <h4 class="text-projects text-center fw-bold pb-3" >Proyek kami</h4>
  <div class="container">
    <div class="row">
      <div class="col">
          <div class="card" style="width: 18rem; color: black; border-radius: 10px;">
              <img src="{% static 'web/img/project1.jpg'%}" class="card-img-top" alt="p1">
                <div class="overlay">
                  <div class="text">Citraland Surabaya</div>
                </div>
            </div>
      </div>
      <div class="col">
          <div class="card" style="width: 18rem; color: black; border-radius: 10px;">
              <img src="{% static 'web/img/project2.jpg'%}" class="card-img-top" alt="p2">
              <div class="overlay">
                <div class="text">Nava Hotel Tawangmangu</div>
              </div>
            </div>
      </div>
      <div class="col">
          <div class="card" style="width: 18rem; color: black;border-radius: 10px;">
              <img src="{% static 'web/img/project4.jpg'%}" class="card-img-top" alt="p3">
              <div class="overlay">
                <div class="text">Pakuwon City Surabaya</div>
              </div>
            </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <a href="{% url 'web:project' %}">Proyek lain</a>
      </div>
    </div>
  </div>   
</section>

<!--<section class="fact" id="fact">
  <div class="container">
    <div class="row">
      <div class="col">
        <h4>Bisakah mengurangi biaya listrik rumah dan sekaligus mengurangi efek rumah kaca? temukan jawaban Anda pada artikel-artikel kami pada link di bawah ini</h4>
        <a href="{% url 'web:project' %}">Artikel</a>
      </div>
      </div>
      
    </div>
  </div>
  
</section>-->

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#DC143C" fill-opacity="1" d="M0,128L1440,192L1440,320L0,320Z"></path></svg>
    
{% endblock %}

ariane/templates/web/product.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
    <section class="product-header">
    </section>

    <section class="product-text1">
        <div class="container">
            <h3>Ariane Water Heater</h3>
            <p>Segment kami bergerak di bidang energi terbarukan. Untuk menunjang visi kami, kami menawarkan beberapa product. Product-product yang kami tawarkan seperti pemanas air matahari, heatpump dan pompa pendorong serta filter air. Untuk informasi lebih lanjut silahkan beralih ke bagian masing-masing di bawah ini.</p>
        </div>
    </section>

    <section class="product-swh">
        <div class="container">
            <h3 class="text-start">Solar Water Heater</h3>
            <a href="{% url 'web:swh' %}">Selanjutnya</a>
        </div>
    </section>

    <section class="product-heatpump">
        <div class="container">
            <h3 class="text-end">Heatpump</h3>
            <a href="{% url 'web:heatpump' %}">Selanjutnya</a>
        </div>
    </section>

    <section class="product-pump">
        <div class="container">
            <h3 class="text-start">Booster Pump and Filter</h3>
            <a href="{% url 'web:pump' %}">Selanjutnya</a>
        </div>
    </section>
{% endblock %}

ariane/templates/web/pump.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

    <section class="pump-text">
        <div class="container">
            <h3>Ariane Bosster Pump</h3>
            <p>Kami menawarkan Booster Pump EQ series yang didesign untuk supply air dan memberi tekanan lebih.</p>
        </div>
    </section>

    <section class="pump-product">
        <div class="container">
            <div class="row pt-4">
                <div class="col-5">
                    <img src="{% static 'web/img/product-pompa.jpg' %}" alt="swh-vacuum">
                </div>
                <div class="col-sm-7 fs-5">
                    <ul>
                        <li>Memiliki design yang compact dan bunyi yang sunyi, sehingga cocok untuk pemakaian rumah tangga</li>
                        <li>Dibuat dari material yang tahan korosi</li>
                        <li>Terdapat sensor dry-running. Sehingga pompa akan otomatis mati jika tidak ada air</li>
                        <li>Dilengkapi dengan teknologi "anti-cycling" yang mencegah pompa untuk secara terus-menerus on dan off pada waktu pemakaian sedikit</li>
                    </ul>
                    <a href="{% static 'web/media/test.pdf' %}" download>Brosur EQ-200</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>Brosur EQ-400</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>Brosur EQ-800</a>
                </div>
            </div>
        </div>
    </section>

    <section class="find-partner-banner">
        <div class="container">
            <a href="{% url 'web:partner' %}">Find Partners</a>
        </div>
    </section>

{% endblock %}

ariane/templates/web/swh.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

    <section class="swh-text">
        <div class="container">
            <h3>Ariane Solar Water Heater</h3>
            <p>Kami menyediakan pemanas air matahari dengan bekerjasama dengan perusahaan di China yang sudah Go Public dan berskala internasional. Disini product kami dibagi menjadi dua bagia. Pertama dengan teknologi kaca vacuum dan yang kedua dengan kaca datar. Setiap teknologi mempunyai kelebihan dan kekurangan masing-masing. Silahkan pergi ke bagian masing-masing untuk mempelajari lebih lanjut </p>
        </div>
    </section>

    <section class="swh-product">
        <div class="container">
            <div class="row pt-4">
                <h4>Vacuum Tube Kollektor</h4>
                <div class="col-sm-5">
                    <img id="swh-vacuum-img" src="{% static 'web/img/swh-vacuum.jpg' %}" alt="swh-vacuum">
                </div>
                <div class="col-sm-7 fs-5">
                    <ul>
                        <li>Pressurized dan indirect heating system dengan heat exchanger</li>
                        <li>Tangki penyimpanan air panas terbuat dari stainless steel SUS 304</li>
                        <li>Untuk seri Ariane C-100 sampai C-300 dengan pipa tembaga heat exchanger</li>
                        <li>Untuk seri Ariane DT menggunakan sistem double tank atau tanki ganda</li>
                        <li>Untuk mencegah heat loss, tangki dibungkus dengan high density polyurethane yang tebal</li>
                        <li>Vacuum tube dengan diameter yang besar (58mm) untuk penyerapan panas yang lebih optimal</li>
                        <li>Dilengkapi elektrik backup bila cuaca mendung atau hujan</li>
                    </ul>
                    <a href="{% static 'web/media/test.pdf' %}" download>brosur C-100</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>brosur C-200</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>brosur C-300</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>brosur DT-150</a>
                </div>
            </div>
            <div class="row pt-4">
                <h4 class="text-end">Flat Plate Kollektor</h4>
                <div class="col-7 fs-5">
                    <ul>
                        <li>Pressurized dan direct heating system</li>
                        <li>Tersedia dalam pilihan tangki air panas dengan stainless steel SUS 316L atau SUS304 dan Enamel</li>
                        <li>Dibungkus dengan high density polyurethane yang tebal untuk meminimalisir heat loss</li>
                        <li>Kaca panel di coating dengan pilihan teknologi black-chrome maupun blue-tec untuk mengoptimalkan penyerapan panas matahari</li>
                        <li>Dilengkapi elektrik backup heater dengan thermostat bilamana cuaca mendung atau hujan</li>
                    </ul>
                    <a href="{% static 'web/media/test.pdf' %}" download>brosur FL-150</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>brosur FL-300</a>
                    <a href="{% static 'web/media/test.pdf' %}" download>brosur split VC-300</a>
                </div>
                <div class="col-5">
                    <img id="swh-flat-img" src="{% static 'web/img/swh-flat.jpg' %}" alt="swh-vacuum">
                </div>
            </div>
        </div>
    </section>

    <section class="find-partner-banner">
        <div class="container">
            <a href="{% url 'web:partner' %}">Find Partners</a>
        </div>
    </section>

{% endblock %}